feat: docker image upload
Ellipsis-Labs/solana-verifiable-build pull request #88
Opened 2024-10-31 02:24 UTC by jacobcreech

2024-11-03 17:08 UTC, MrG9090 approved these changes

2024-11-04 18:34 UTC, ngundotra commented on update_image_whitelist.py
> -            raise Exception(f"Failed to get Docker images: {response.status_code} {response.text}")
keep this

2024-11-04 18:36 UTC, ngundotra requested changes

2024-11-04 18:36 UTC, ngundotra commented on update_image_whitelist.py
> +    results = response.json()
remove anything pointing to the old version

2024-11-12 02:46 UTC, merged